import { ClashDisplay, inter } from "../utils/customFonts";
import "./globals.css";

export const metadata = {
  title: "IDEATECH3",
  description: "Generated by create next app",
  icons: "./logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ClashDisplay.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
